### ISSUE TITLE
improve the theme 

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/ide#1]
right now it's just bootstrap 101. 
we need it better branded (using CB color scheme).

**Comment by yashovardhanagrawal** [comment]
I am quite new to open source... if this issue is open can you please explain me a bit what to do here?

**Comment by championswimmer** [comment]
The entire bounty might not be applicable to all pull requests. If someone makes partial improvements to the theme, we'd accept that as well, but award less than 100 bounty points.

**Comment by hereisnaman** [comment]
Improved UI. Gave a brand look. Added footer. Updated navbar. Added style.

[Pull Request](https://github.com/coding-blocks/ide/pull/12)

## Updated Navbar and Editor Style
![image](https://cloud.githubusercontent.com/assets/22571395/26148847/aac92a96-3b15-11e7-88a5-b2213c1f3565.png)

## Added Footer
![image](https://cloud.githubusercontent.com/assets/22571395/26148875/c19e2000-3b15-11e7-807b-90e6aadc2fea.png)

**Comment by championswimmer** [comment]
nicely done

**Comment by hereisnaman** [comment]
@championswimmer thanks. Well will love to tweak the shotlr page too, with some more ideas. #greedybountyhunter
