### ISSUE TITLE
use pastebin to save files instead of own backend

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/ide#101]
an overhead that shouldn't  our headache
(why save random code bits for unlimited time on our expense, when there is pastebin for free)
https://www.npmjs.com/package/pastebin-js

**Comment by Prajjwal** [comment]
Create a Coding Blocks account and email me the application secrets. Pretty sure this is against their Terms of Service, though.

**Comment by omerjerk** [comment]
@championswimmer We are saving the files in our postgres db. I don't think it is that much of an overhead.

**Comment by championswimmer** [comment]
@Prajjwal 

Pastebin API key  = 8783a2147bcd74d8b5f3afc93644b3d4

**Comment by omerjerk** [comment]
@championswimmer Close this issue if not required anymore.
