### ISSUE TITLE
Add support for C#

### ISSUE THREAD

**Issue by omerjerk** [coding-blocks/ide#102]
Our compilation engine now supports C#. The language code for C# is 'csharp'.
Adding support for this should be trivial now.

**Comment by hereisnaman** [comment]
Sample Code ?

**Comment by omerjerk** [comment]
Yes. sample code also needs to be added.

**Comment by hereisnaman** [comment]
"hello world program in c#" just added to google search history.

**Comment by omerjerk** [comment]
Cool.
