### ISSUE TITLE
Use vuex-persistedstate

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/ide#106]
Take a look into ~~https://github.com/robinvdvleuten/vuex-persistedstate~~ http://npmjs.com/vuex-persist

It can avoid a lot of redundant code to persist store state to localStorage.  We should move to this

**Comment by hereisnaman** [comment]
okay

**Comment by championswimmer** [comment]
BROOOOOOO WTFFFFFFF
use http://npmjs.com/vuex-persist

**Comment by championswimmer** [comment]
Even alligator recommends mine - https://alligator.io/vuejs/vuex-persist-state/

**Comment by hereisnaman** [comment]
haha cool

**Comment by abhishek97** [comment]
Oh forgot about yours @championswimmer 😂 , the api seems similar, we can switch easily :)

**Comment by hereisnaman** [comment]
@abhishek97 already vue-persist is getting used. Do I get the bounty to mention this or to remove the other package as dependency? :p
