### ISSUE TITLE
No option/button to toggle the IDE to full screen.

### ISSUE THREAD

**Issue by ashish1500616** [coding-blocks/ide#11]
There should be an option to toggle the IDE to fullscreen.

**Comment by darshkpatel** [comment]
@championswimmer  assign the issue to me ?

**Comment by astu9880** [comment]
@ashish1500616 reviews?

**Comment by astu9880** [comment]
@ashish1500616 reviews on #18?

**Comment by sirjan13** [comment]
@ashish1500616  Kindly Review  #22
