### ISSUE TITLE
Add language support for Node

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/ide#123]
Currently, the IDE supports `javascript` in a browser context. However, the judgeblocks API support nodeJs also. Allow language Support for nodeJs. 

To have judge API compile run nodeJs, `language` key should be set to `js`, more info about the API here: https://codingblocks.com/judge-blocks-docs/

**Comment by hereisnaman** [comment]
resolved in: https://github.com/coding-blocks/ide/pull/143
