### ISSUE TITLE
Page is not responsive .

### ISSUE THREAD

**Issue by ashish1500616** [coding-blocks/ide#13]
The Desktop version of the site opens up on
![screen shot 2017-05-17 at 3 59 15 pm](https://cloud.githubusercontent.com/assets/19726282/26149924/dd92f4e4-3b19-11e7-956f-723a49998753.png)
 phone

**Comment by bhavyaagg** [comment]
@omerjerk what should be the changes for this issue?

**Comment by ashish1500616** [comment]
The page should be responsive so that the users does not have to zoom into the page to perform operations.

**Comment by hereisnaman** [comment]
Resolved: https://github.com/coding-blocks/ide/pull/17
