### ISSUE TITLE
The URL Shortner for sharing isn't working 

### ISSUE THREAD

**Issue by flaredragon** [coding-blocks/ide#146]
In the share option the Shortened URL is coming up to be undefined.
![screenshot from 2018-05-29 17-27-08](https://user-images.githubusercontent.com/29121452/40657465-9b9d7a1c-6365-11e8-9095-51c2ce1e505b.png)

**Comment by ananay** [comment]
This needs to be fixed on the production server in order to fix this issue
https://github.com/coding-blocks/shortlr/issues/73

**Comment by ananay** [comment]
@championswimmer The shortlr server asks for a secret in order to make shortlinks and I don't know the secret that's running on the prod server. Could you please help me with this step?

**Comment by hereisnaman** [comment]
@ananay there is a backend for the ide https://github.com/coding-blocks/ide-backend . You can run it locally and do the testing.

**Comment by siddhant1** [comment]
Will take this one

**Comment by abhishek97** [comment]
This issue is no longer valid, as `cb.lk` isn't public anymore.
