### ISSUE TITLE
code doesn't change with language

### ISSUE THREAD

**Issue by till-tomorrow** [coding-blocks/ide#149]
The code doesn't change with language. It happens when changes are made in the predefined code.
Example, if the existing code is modified to print to print("hi") instead of "Hello World!" and then the code is run, then changing the language doesn't change the default code that should follow when the programming language changes.

Refer the following image for more clarity.

![code doesnt change with lang when changes are made in predefined code](https://user-images.githubusercontent.com/21954525/41059184-75c36600-69e9-11e8-8ac6-1330b116cd65.JPG)

**Comment by abhishek97** [comment]
It is the intedend behaviour.

![1u9jq5](https://user-images.githubusercontent.com/8109774/41059379-0bb1637e-69ea-11e8-97b8-85087194f90b.jpg)
