### ISSUE TITLE
[enhancement] provide spell check

### ISSUE THREAD

**Issue by till-tomorrow** [coding-blocks/ide#163]
spell check function to correct the users as they type
![spell check](https://user-images.githubusercontent.com/21954525/42260765-48d8bc6c-7f83-11e8-8a5c-3a057bb5d6dd.JPG)

**Comment by abhishek97** [comment]
I'm not sure if this is a good idea. I would like suggestions based on spelling but autocorrect for code, no thank you.

**Comment by championswimmer** [comment]
nah. the idea isn't to turn it into IntelliJ or Webstorm.
