### ISSUE TITLE
Scrolling issue in ide

### ISSUE THREAD

**Issue by witty123** [coding-blocks/ide#167]
Scrolling doesn't work in IDE. Code editor part should be scrollable.

**Comment by architkshk** [comment]
works for me
@witty123 
![peek 2018-07-31 14-59](https://user-images.githubusercontent.com/5001704/43451369-6689dd4a-94d2-11e8-8fa4-1e87b6cc5c89.gif)

**Comment by firefinchdev** [comment]
@witty123 
Done #168 
Pls Review.
