### ISSUE TITLE
Fix Navbar UI

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/ide#177]
The nav-bar breaks when you change to python

<img width="1440" alt="Screen Shot 2019-05-04 at 9 05 49 PM" src="https://user-images.githubusercontent.com/8109774/57181379-7b184b80-6eb0-11e9-9b6c-69d9f4c23fad.png">

**Comment by ManimalaMariappan** [comment]
Hi,
When I changed to python, I didn't find any breaks in the navbar.

**Comment by ManimalaMariappan** [comment]
Hi,
When I changed to python, I didn't find any breaks in my screen.

**Comment by milind-soni** [comment]
> Hi,
> When I changed to python, I didn't find any breaks in my screen.

neither did i

**Comment by championswimmer** [comment]
Depends on screen resolution.

**Comment by hereisnaman** [comment]
Better have dropdown menus. 

Move new, save, download, upload under 1 menu and saved codes, logout under the user name menu.

**Comment by abhishek97** [comment]
Yes, seems good

**Comment by diru1100** [comment]
Does the break persist if you zoom out your chrome screen?

**Comment by sachin235** [comment]
The navbar breaks for all languages on zooming. Otherwise it is fine for all.
Is the issue specific for Python??

**Comment by abhishek97** [comment]
Just to clarify, this has to do with responsiveness and not some particular language. We need a responsive Navar.

**Comment by siddhant1** [comment]
Working!

**Comment by Manvi07** [comment]
Has this issue been resolved?

**Comment by hardik0899** [comment]
I changed to python and tried.. but screen does'nt broke sir

**Comment by dhwaj1902** [comment]
what actually you want, when someone writes python.

**Comment by lukelima** [comment]
It still breaks
![image](https://user-images.githubusercontent.com/45904744/81890875-6370aa00-957d-11ea-850a-7b3b68a5ad49.png)

I guess the author wants something like this:
![image](https://user-images.githubusercontent.com/45904744/81891271-64eea200-957e-11ea-9477-28bc520e2c21.png)

**Comment by paras151** [comment]
I think #244 already solves it

**Comment by hereisnaman** [comment]
closing this in favor of https://github.com/coding-blocks/ide/issues/277
