### ISSUE TITLE
Use Judge2

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/ide#182]
We wish to use new Judge system to run code on online ide
you can find docs for the new judge here: https://judge2.codingblocks.com/docs/

Judge Repo: https://github.com/coding-blocks/judge-compose
All the required judge components are available here: https://github.com/coding-blocks

The new judge api is hosted at https://judge2.codingblocks.com/api

Requirements:

- [ ] Must POST to judge2 api to run code, use appropriate language keys 
- [ ] Use Poll mode to poll for result

**Comment by AdityaSrivast** [comment]
@abhishek97 claiming it

**Comment by siddhant1** [comment]
Will try to fix this if there is no pr already

**Comment by Manit1** [comment]
@abhishek97 How can I get an API key to test my application? or should I setup the judge locally?

**Comment by abhishek97** [comment]
@Manit1 yes for now, you must setup judge locally and use the api key in your local db.

**Comment by manigedit** [comment]
@abhishek97 can you please give me a hint where to find the api key? I have setup the judge and the project locally

**Comment by AdityaSrivast** [comment]
@abhishek97 how to get the API to test locally after docker-compose up command?

**Comment by AdityaSrivast** [comment]
@abhishek97 is judge2 api live? I am able to make only options request to the local server.

**Comment by AllenAJ** [comment]
Can you guide me on how i can setup polling for submission result?

**Comment by snehalbaghel** [comment]
@abhishek97 Where so I put the API key in the ide-backend?

**Comment by parshnt** [comment]
Hi, I would like to work on this

**Comment by snehalbaghel** [comment]
@abhishek97 can you take a look at my PRs?
