### ISSUE TITLE
Correct grammatical mistake in readme

### ISSUE THREAD

**Issue by parammittal16** [coding-blocks/ide#201]
There are some grammatical issues in Readme file.
I want to correct them and work on this issue as of Hackoberfest.

**Comment by parammittal16** [comment]
@abhishek97 plz review the PR. Can we add hacktoberfest labels here?

**Comment by championswimmer** [comment]
Contribution != fixing grammar. 

We would like to encourage you to contribute something to the core functionality of the project. Please do not fix typos in README just for the sake of a competition. The purpose of Hacktoberfest is to increase people participating in open source projects and learn some new skills in the process.
