### ISSUE TITLE
There is no link to coding blocks website from the top right coding blocks image

### ISSUE THREAD

**Issue by leelatanniru** [coding-blocks/ide#216]
When I click on the coding blocks image on the top right corner of the menu bar, it is not navigating to the coding blocks website.
![image](https://user-images.githubusercontent.com/22635016/66508590-0e544d80-eaef-11e9-913c-3e4caf9bd4ea.PNG)

**Comment by abhishek97** [comment]
Yes you can. Good ahead

**Comment by leelatanniru** [comment]
I have submitted a pull request for the same yesterday. @abhishek97 could you please review it.
