### ISSUE TITLE
Not able to run locally using command 'npm run dev'

### ISSUE THREAD

**Issue by harrymaurya05** [coding-blocks/ide#268]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle cb-ide@1.0.0~predev: cb-ide@1.0.0
6 silly lifecycle cb-ide@1.0.0~predev: no script for predev, continuing
7 info lifecycle cb-ide@1.0.0~dev: cb-ide@1.0.0
8 verbose lifecycle cb-ide@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle cb-ide@1.0.0~dev: PATH: /usr/share/npm/bin/node-gyp-bin:/media/harry/New Volume1/codingEditor/ide/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/harry/bin:/opt/java/bin:/home/harry/bin:/opt/java/bin
10 verbose lifecycle cb-ide@1.0.0~dev: CWD: /media/harry/New Volume1/codingEditor/ide
11 silly lifecycle cb-ide@1.0.0~dev: Args: [ '-c',
11 silly lifecycle   'webpack-dev-server --inline --progress --config build/webpack.dev.conf.js' ]
12 silly lifecycle cb-ide@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle cb-ide@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: cb-ide@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid cb-ide@1.0.0
16 verbose cwd /media/harry/New Volume1/codingEditor/ide
17 error Linux 5.3.0-26-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error cb-ide@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
22 error Exit status 1
23 error Failed at the cb-ide@1.0.0 dev script 'webpack-dev-server --inline --progress --config build/webpack.dev.conf.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the cb-ide package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs cb-ide
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls cb-ide
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hereisnaman** [comment]
Please check line 23 of the logs.
