### ISSUE TITLE
Add option to import input from file

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/ide#275]
Add a button in the input box header to load input from text file on the system.

![Screenshot 2020-05-16 at 1 18 28 AM](https://user-images.githubusercontent.com/22571395/82090407-2b9b6b00-9713-11ea-9174-9cdd9d504b40.png)

**Comment by guptapranav4299** [comment]
is this issue open or closed?

**Comment by hereisnaman** [comment]
it is open

**Comment by guptapranav4299** [comment]
@hereisnaman please assign me this issue

**Comment by RohanGoel107** [comment]
@hereisnaman I would like to work on this issue

**Comment by irohan107** [comment]
@hereisnaman I would like to work on this issue

**Comment by ankiiitraj** [comment]
Hi @hereisnaman, I have made a PR regarding this issue. Can you assign yourself as reviewer. Thanks

**Comment by ankiiitraj** [comment]
Pull request: https://github.com/coding-blocks/ide/pull/283

**Comment by hereisnaman** [comment]
> Pull request: #283

Please make separate PRs for each issue.
