### ISSUE TITLE
Add option to download output

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/ide#276]
Add button in the output header to download the result into a file.

![Screenshot 2020-05-16 at 1 20 30 AM](https://user-images.githubusercontent.com/22571395/82090596-7fa64f80-9713-11ea-986a-317319067a81.png)

**Comment by gauravkhurana97** [comment]
@hereisnaman I want to work on this issue!

**Comment by hereisnaman** [comment]
Assigned to you @gauravkhurana97

**Comment by kgoel9899** [comment]
Other people can't work on an issue if it has already been assigned?

**Comment by hereisnaman** [comment]
> Other people can't work on an issue if it has already been assigned?

You can work, the better solution will be merged.

**Comment by jugshaurya** [comment]
@hereisnaman, can you tell me the tech stack used/required for this issue to be resolved

**Comment by ankiiitraj** [comment]
Hi @hereisnaman , I have made a PR for this. Can you assign yourself as reviewer. Thanks
PR : https://github.com/coding-blocks/ide/pull/283
