### ISSUE TITLE
The right top coding blocks image tag has no link attached

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/ide#278]
The image tag is just static. It should direct to https://online.codingblocks.com/.
![image](https://user-images.githubusercontent.com/52792904/82109494-011dd200-9754-11ea-924c-f5f68fb1a40f.png)
![Screenshot from 2020-05-16 09-03-30](https://user-images.githubusercontent.com/52792904/82109516-35918e00-9754-11ea-8ebb-45828572efe6.png)

**Comment by hereisnaman** [comment]
Issue already exists. Closing this in favor of https://github.com/coding-blocks/ide/issues/216
