### ISSUE TITLE
Automatically Select Language based upon file-extension

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/ide#28]
Add a small functionality to automatically choose the language, when a source code file is being uploaded on www.codingblocks.com/ide

**Comment by abhishek97** [comment]
@prateek27 please review #29 

UI Screenshot :
![screen shot 2017-05-24 at 11 44 02 pm](https://cloud.githubusercontent.com/assets/8109774/26418717/e6833cbe-40da-11e7-907a-cfae5339d0c6.png)

**Comment by sirjan13** [comment]
Just a **suggestion** : 
It would be great if once we select the language the whole word "Language" is substituted by the Language selected.This is what traditional ide's like codechef and hackerrank have.

**Comment by prateek27** [comment]
Yes I like this suggestion.Send a PR, bounty 20 points

**Comment by sirjan13** [comment]
who has to do this earlier i got a mail saying make a pr,bounty 20

**Comment by hereisnaman** [comment]
@prateek27 already resolved with file upload restrictions and lang variable update and button html update. PR: https://github.com/coding-blocks/ide/pull/30

Also please check: https://github.com/coding-blocks/ide/pull/26

**Comment by abhishek97** [comment]
@prateek27 Default lang is C++ now, and shows only Current selected lang in the corner.

**Comment by abhishek97** [comment]
@prateek27  @championswimmer  Review https://github.com/coding-blocks/ide/pull/29 for this issue?

**Comment by hereisnaman** [comment]
@abhishek97 The bug was reported by me and has been already resolved under my PR.
