### ISSUE TITLE
Fix short url not loading issue

### ISSUE THREAD

**Issue by maze-runnar** [coding-blocks/ide#280]
![Screenshot from 2020-05-16 12-10-08](https://user-images.githubusercontent.com/56407566/82112807-4cdd7500-976e-11ea-8094-676c13927299.png)

**Comment by maze-runnar** [comment]
I am working on this, if this is valid

**Comment by ankiiitraj** [comment]
Hi @hereisnaman , if this qualifies for bounty please add one. Thanks

**Comment by maze-runnar** [comment]
@hereisnaman I want to work on this, Can you plz assign it to me.

**Comment by ankiiitraj** [comment]
can approach to solve this issue, little help would be appreciated. Thanks
