### ISSUE TITLE
View->Layout of input,output pane

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/ide#282]
The bottom input and output pane takes lot of space and is inconvenient when we code. We can have the input and output pane to the right side, this setup is quite convenient for coding and many programmers prefers this. 
![Screenshot from 2020-05-16 09-10-06](https://user-images.githubusercontent.com/52792904/82113285-8d3ef200-9772-11ea-8c10-04ae7863b172.png)
 This layout view. One can get more space for the code part.

**Comment by hereisnaman** [comment]
@mnb27 Good idea. We can try it out. Can you share screenshots about how it will look. We will also need a button to switch between bottom and right positions.

**Comment by mnb27** [comment]
@hereisnaman  Yup, a switch button to toggle between the two layout views. Have a look at the screenshots.
![a](https://user-images.githubusercontent.com/52792904/82119383-a60fcd80-979b-11ea-879d-3f3b7297c4f9.png)
![Screenshot from 2020-05-16 17-34-33](https://user-images.githubusercontent.com/52792904/82119408-e7a07880-979b-11ea-8806-5b9572547ddf.png)

**Comment by mnb27** [comment]
@hereisnaman Please assign bounties to this issue. I want to work on this.

**Comment by hereisnaman** [comment]
@mnb27 
Some ideas:

- Lets have a 6:4 split.
- The input-output section should be full height when in vertical split. Below the navbar obviously.
- Have a layout toggle button like in the firefox browser with only dock to bottom and dokc to right options. In the dock to bottom layout have the button displayed in the Output header to the left of the copy icon. In the dock to right layout, have to button displayed in the Input header.
- default state should be dock to bottom

**Comment by mnb27** [comment]
@hereisnaman Toggle button on the Input bar.
![Screenshot from 2020-05-18 14-32-27](https://user-images.githubusercontent.com/52792904/82206171-5eb54880-9925-11ea-829b-ec94d701def9.png)
Any Suggestions ?

**Comment by dakshkhetan** [comment]
@hereisnaman I have also worked on this issue. Please review PR #311.
Thanks!

**Comment by hereisnaman** [comment]
@mnb27 toggle button does not tell what is its use case. Have a drop down like this one. Use the kabab menu icon as dropdown toggle.

<img width="327" alt="Screenshot 2020-05-18 at 6 40 49 PM" src="https://user-images.githubusercontent.com/22571395/82216820-23bc1080-9937-11ea-942a-82cb4fd74c7b.png">

**Comment by hereisnaman** [comment]
> @mnb27 toggle button does not tell what is its use case. Have a drop down like this one. Use the kabab menu icon as dropdown toggle.
> 
> <img alt="Screenshot 2020-05-18 at 6 40 49 PM" width="327" src="https://user-images.githubusercontent.com/22571395/82216820-23bc1080-9937-11ea-942a-82cb4fd74c7b.png">

@dakshkhetan can you make the same changes.

**Comment by hereisnaman** [comment]
First one to implement the complete functionality with better code will have his PR get merged.

**Comment by mnb27** [comment]
@hereisnaman You meant just to change the icon to kabab-menu icon or something more to be added?

**Comment by hereisnaman** [comment]
> @hereisnaman You meant just to change the icon to kabab-menu icon or something more to be added?

Change the icon, add the dropdown menu. Align the icons to the right side of the header always.

Also I see the input output section is overlaying the editor right now. Its really not a 6:4 split. 

I would like to see a version with the editor width actually reduced to 60% and the io section rendered in the left 40% width adjacent to the editor.

Will compare both the layouts and then we can decide.

**Comment by mnb27** [comment]
@hereisnaman Ok,got it!! I will make the required changes.

**Comment by mnb27** [comment]
@hereisnaman GIF Below!! Suggest changes if required else if will make pr.
![ide](https://user-images.githubusercontent.com/52792904/82239452-64775200-9956-11ea-8854-d469e0205a34.gif)

**Comment by hereisnaman** [comment]
> @hereisnaman GIF Below!! Suggest changes if required else if will make pr.

- auto close the dropdown menu on layout switch
- make the drodown dark

Waiting for the other layout implementation too.

**Comment by mnb27** [comment]
@hereisnaman Yes the dropdown menu automatically closes on layout switch.
I will make the dropdown dark.

**Comment by hereisnaman** [comment]
> @hereisnaman Yes the dropdown menu automatically closes on layout switch.
> I will make the dropdown dark.

forgot one thing. kebab icon has 3 vertical dots.

**Comment by mnb27** [comment]
@hereisnaman Done:) #312 PR
Changed kebab icon.
Kindly review it!

**Comment by hereisnaman** [comment]
@mnb27 @dakshkhetan You both have done a great job. Few things in both the PRs are missing that shall be fixed.

I was wondering if you two can work together on this, let me know and I can explain the further changes required then.

**Comment by hereisnaman** [comment]
@dakshkhetan you have not set the max width of the input output container in the vertical view to 550px. Please create a PR fixing it. 

It will also require you to set the editor max-width = calc(100vh - 550px).

**Comment by mnb27** [comment]
> @mnb27 @dakshkhetan You both have done a great job. Few things in both the PRs are missing that shall be fixed.
> I was wondering if you two can work together on this, let me know and I can explain the further changes required then.

@hereisnaman Thanks!! and I would like to work on the further required changes.

**Comment by hereisnaman** [comment]
> > @mnb27 @dakshkhetan You both have done a great job. Few things in both the PRs are missing that shall be fixed.
> > I was wondering if you two can work together on this, let me know and I can explain the further changes required then.
> 
> @hereisnaman Thanks!! and I would like to work on the further required changes.

Actually I just did that myself.
