### ISSUE TITLE
Coding Blocks logo

### ISSUE THREAD

**Issue by samjain2907** [coding-blocks/ide#284]
![Selection_002](https://user-images.githubusercontent.com/53353139/82114250-43a5d580-9779-11ea-8c5a-006f580cb6ce.png)

The Coding Blocks logo is non-clickable. It should redirect to the Coding Blocks website on clicking.

**Comment by hereisnaman** [comment]
Duplicate Issue. Closing this in favor of https://github.com/coding-blocks/ide/issues/216
