### ISSUE TITLE
sharable-link not appearing in "share" modal popup

### ISSUE THREAD

**Issue by dakshkhetan** [coding-blocks/ide#292]
Screenshot for reference:

<img width="1440" alt="issue" src="https://user-images.githubusercontent.com/43447509/82141405-32c99280-9853-11ea-8998-e7d794d53d58.png">

**Comment by dakshkhetan** [comment]
@hereisnaman I would like to work on this issue. Please assign this to me. Thanks! 😀

**Comment by hereisnaman** [comment]
Closing this in favor of https://github.com/coding-blocks/ide/issues/280
