### ISSUE TITLE
Hovering over links for facebook, twitter and email on share model is text type cursor and not pointer type cursor.

### ISSUE THREAD

**Issue by ankiiitraj** [coding-blocks/ide#294]
Steps to reproduce:
1. Click on share link/button on menubar.
2. Hover on the links below the text field i.e. on facebook and others.
Suggested fix : 
I see the class used here https://github.com/coding-blocks/ide/blob/7353268d2bb427ed4c557cc8f5631a9c233e3b2d/src/components/editor/Share.vue#L121
https://github.com/coding-blocks/ide/blob/7353268d2bb427ed4c557cc8f5631a9c233e3b2d/src/components/editor/Share.vue#L122
But this doesn't get applied. I can't figure out why.
Using inline css fixes this.

**Comment by ankiiitraj** [comment]
Hi  @hereisnaman Have a look here. Should I use inline css and get rid of the socialShare class?

Also if this qualifies please add ounty to this. Thanks

**Comment by mnb27** [comment]
#335 PR
Preview here: https://deploy-preview-335--cb-ide.netlify.app/

If the issue qualifies ,review and merge this PR.
