### ISSUE TITLE
Fix MenuBar height for small displays

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/ide#302]
<1200px

![Screenshot 2020-05-17 at 11 56 58 PM](https://user-images.githubusercontent.com/22571395/82156668-2b79a780-989a-11ea-9c9c-5febb4c95e6a.png)

**Comment by ankiiitraj** [comment]
Hi @hereisnaman can you slightly brief on what to do. Thanks!

**Comment by dakshkhetan** [comment]
@hereisnaman I have worked on this issue. Please review PR #306 😀
Thanks!
