### ISSUE TITLE
'save' option not appearing in nav-bar

### ISSUE THREAD

**Issue by dakshkhetan** [coding-blocks/ide#303]
<img width="1440" alt="Screenshot 2020-05-17 at 11 55 46 PM" src="https://user-images.githubusercontent.com/43447509/82156836-59132080-989b-11ea-92dd-3a8456a4c837.png">

**Comment by dakshkhetan** [comment]
@hereisnaman I have fixed this issue. Please review PR #304 😀
Also, if eligible, please assign BOSS label and bounty.
Thanks!

**Comment by hereisnaman** [comment]
You can claim it.
