### ISSUE TITLE
Bind ctrl+s shortcut with Save to cloud action

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/ide#305]
Currently the ctrl+s shortcut is attached with the download file action. Change it to call the save action rather.

Update the shortcut info accordingly.

![Screenshot 2020-05-18 at 12 32 17 AM](https://user-images.githubusercontent.com/22571395/82157437-0c314900-989f-11ea-9a5c-aa2e8f6f92d3.png)

**Comment by dakshkhetan** [comment]
@hereisnaman I have worked on this issue. Please review PR #307 😀
Thanks!

**Comment by ankiiitraj** [comment]
hi @hereisnaman I have fixed this issue along with the the issue that **shortcuts were not working**. I added eventListener now it is working fine.

**Comment by hereisnaman** [comment]
> hi @hereisnaman I have fixed this issue along with the the issue that **shortcuts were not working**. I added eventListener now it is working fine.
> Please review the PR. Thanks!

Can you open a separate issue and PR to just fix the working of shortcuts. This issue is closed.

**Comment by hereisnaman** [comment]
@dakshkhetan @ankiiitraj You both can claim 100 bounty points for this.
