### ISSUE TITLE
[Error 404-Not Found ]Coding Blocks Judge API

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/ide#309]
CB Judge API Documentation is not attached.
![Screenshot from 2020-05-18 10-34-59](https://user-images.githubusercontent.com/52792904/82176103-62c87280-98f3-11ea-80c9-7c3c987630b9.png)

**Comment by hereisnaman** [comment]
Where is it mentioned that the judge api is served here? Also this project contains only frontend for the ide. Closing this.
