### ISSUE TITLE
Bug:Any file can be uploaded

### ISSUE THREAD

**Issue by sirjan13** [coding-blocks/ide#32]
Any file can be uploaded currently which is not desired. We need to restrict the acceptable file extensions  so that user cant upload any file having a different extension.

@omerjerk @prateek27 please review

**Comment by abhishek97** [comment]
@omerjerk @prateek27 I dont think this is a good idea. The file extension 
 is nothing but a windows construct. People using *nix based os hardly focus on file extension. Personally, i'll be totally mad if it says that my .txt cannot be loaded. Extensions should not get in the way here.

**Comment by hereisnaman** [comment]
@abhishek97 but you cannot allow uploading of an img file and we can add exception to allow text file and set lang to default lang i.e. C.

**Comment by abhishek97** [comment]
It doesn't matter really, going by this if user changes the ext of img file to .c then it uploads it anyways. If a users chooses an img, let him get gibberish.. the ide is running on his browser after all. Also there can be many variants of extensions for a language .h , .cxx,. .py3 ,.pypy . We cannot get them all. There is fundamentally no difference between an img file and .cpp file on OS level.

**Comment by hereisnaman** [comment]
@abhishek97 Yeah your point is valid :). 

@prateek27 removing file extension restriction feature from my PR: https://github.com/coding-blocks/ide/pull/30

**Comment by prateek27** [comment]
@sirjan13 Closing this issue.
