### ISSUE TITLE
InOutBox icons hover & focus color

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/ide#321]
fa-icons of InOutBox doesn't glow red on hover and focus like download icon.

**Comment by hereisnaman** [comment]
@mnb27 few more issues are there in the Gondor project, you can check them out.

**Comment by mnb27** [comment]
> @mnb27 few more issues are there in the Gondor project, you can check them out.

@hereisnaman Sure!! Thanks

**Comment by mnb27** [comment]
@hereisnaman Fixed this issue.  #322 PR
Check Preview:
https://deploy-preview-322--cb-ide.netlify.app/
