### ISSUE TITLE
Add save file modal

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/ide#323]
Currently the filename input field is in the status bar at the bottom. On saving the file, the name is set to untitled if the value of the field is null.

On saving check if any file name exists, otherwise show a modal with the input field for the same and a save button in the modal footer. 

The value of the input field should be initialized by `code.<lang_ext>`. You need to maintain a map of extensions per language as being done for the download modal. Use a common lang-ext map for both the modals and add extensions for the missing langs.

Also in the download modal initialize the value of input field used in that modal for the name of file to be downloaded with the filename input in the status, but if the filename input is empty in the status, initialize in the similar way as already being done.

The modal should have dark bg.

**Comment by prathambatra** [comment]
I will give it a try.

**Comment by prathambatra** [comment]
@hereisnaman If filename exists only then we have to show the modal with save option.. right?

**Comment by hereisnaman** [comment]
> @hereisnaman If filename exists only then we have to show the modal with save option.. right?

Opposite

**Comment by prathambatra** [comment]
okay, it means if filename exists then the user will have 2 files with the same name, that's fine?

**Comment by hereisnaman** [comment]
> okay, it means if filename exists then the user will have 2 files with the same name, that's fine?

why would there be 2 file? Please re-read the description.

**Comment by prathambatra** [comment]
@hereisnaman if i am running this project in dev. I also need to run API locally right? do also need to give some working firebase config.

**Comment by prathambatra** [comment]
> @hereisnaman if i am running this project in dev. I also need to run API locally right? do also need to give some working firebase config.

because i am unable to use savecode feature locally.

**Comment by MohdImran001** [comment]
When running npm install I am facing this error:- `gyp ERR! stack Error: `make` failed with exit code: 2`

**Comment by prathambatra** [comment]
@MohdImran001  show full terminal screenshot

**Comment by MohdImran001** [comment]
I updated the firebase version from 5 to 7 then it worked fine. But now when I am running `npm start` I am having the following error.
![Screenshot from 2020-05-21 01-33-32](https://user-images.githubusercontent.com/42844688/82492186-692d3900-9b03-11ea-9d7e-0297e8560566.png)

**Comment by prathambatra** [comment]
npm i monaco-editor --save 
do this
