### ISSUE TITLE
add stub and theme for lang: kotlin

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/ide#324]
We just introduced the support of a new language in our judge. Let's support it on our IDE as well.

- [ ] Add langMode [here](https://github.com/coding-blocks/ide/blob/master/src/components/editor/MonacoEditor.vue#L9) compatible with monaco editor
- [ ] Add a sample hello world code [here](https://github.com/coding-blocks/ide/blob/master/src/assets/js/sample-source.js) and export the language
    ```
     fun main(args: Array<String>) {
        println("Hello World")
     }
    ```

Test your submissions:
- [ ] Is the syntax highlighting working?
- [ ] Is the stub shown when language is changed?

**Comment by ankiiitraj** [comment]
> We just introduced the support of a new language in our judge. Let's support it on our IDE as well.
> 
>     * [ ]  Add langMode [here](https://github.com/coding-blocks/ide/blob/master/src/components/editor/MonacoEditor.vue#L9) compatible with monaco editor
> 
>     * [ ]  Add a sample hello world code [here](https://github.com/coding-blocks/ide/blob/master/src/assets/js/sample-source.js) and export the language
>       ```
>        fun main(args: Array<String>) {
>           println("Hello World")
>        }
>       ```
> 
> 
> Test your submissions:
> 
>     * [ ]  Is the syntax highlighting working?
> 
>     * [ ]  Is the stub shown when language is changed?

Hi @jatinkatyal13 kindly review the PR. Thanks
