### ISSUE TITLE
Add Margin to the Notification

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/ide#326]
Add top margin to the notification box to not overlap the navbar.

<img width="321" alt="Screenshot 2020-05-20 at 5 29 47 AM" src="https://user-images.githubusercontent.com/22571395/82389957-0aac8000-9a5b-11ea-84fb-5b3daa03ac08.png">

**Comment by namanrai** [comment]
I would like to work on it but can't find the code for the notification.
