### ISSUE TITLE
Configurations issue: When i click Run on my local setup it only give me red notification 

### ISSUE THREAD

**Issue by gurrrung** [coding-blocks/ide#328]
The only red notification which says:
![Screenshot from 2020-05-20 08-43-39](https://user-images.githubusercontent.com/30543444/82401157-ad262c80-9a76-11ea-89a2-907b1116e260.png)

**Comment by hereisnaman** [comment]
You need to have ide-backend setup.

**Comment by gurrrung** [comment]
Thanks, that helped.
