### ISSUE TITLE
Bug:Theme and Upload not displayed in responsive design

### ISSUE THREAD

**Issue by SidharthBansal** [coding-blocks/ide#34]
In the full screen mode, we see the ide like this
![image](https://cloud.githubusercontent.com/assets/20972099/26463754/007db586-41a3-11e7-85be-938faec983e8.png)

But when we shrink the window size the window doesnt show Theme and Upload options
![image](https://cloud.githubusercontent.com/assets/20972099/26463723/e8d5c3d8-41a2-11e7-86dc-00475c711a57.png)
The bootsrap is not working for these two buttons
Please see @prateek27 @championswimmer

**Comment by hereisnaman** [comment]
resolved: https://github.com/coding-blocks/ide/pull/35

**Comment by SidharthBansal** [comment]
Shall I also get bounty for figuring out bug?

**Comment by SidharthBansal** [comment]
Shall I also get bounty for telling a bug?

**Comment by hereisnaman** [comment]
This project unlike others don't have bug/suggestion bounty as for now, but you can always talk this out with @championswimmer @prateek27.
BTW thanks a lot for reporting the bug.

**Comment by hereisnaman** [comment]
@SidharthBansal you can verify that the bug is not present at http://namankumar.me/ttt/
