### ISSUE TITLE
Syntax color highlighting not working for 'Kotlin' language

### ISSUE THREAD

**Issue by dakshkhetan** [coding-blocks/ide#343]
<img width="740" alt="kotlin issue" src="https://user-images.githubusercontent.com/43447509/82431303-1bd1ad00-9aac-11ea-9516-c1143e28646c.png">

**Comment by dakshkhetan** [comment]
Please assign BOSS label and bounty, thanks! 😀

**Comment by ankiiitraj** [comment]
Hi @dakshkhetan Did you tested by making the state -> language: "kotlin" ?

**Comment by dakshkhetan** [comment]
> Hi @dakshkhetan Did you tested by making the state -> language: "kotlin" ?

Yes. Refer PR #344, it is not working in production because Kotlin support was added in v0.16.0 onwards.

**Comment by ankiiitraj** [comment]
I got the point I have tested it on v0.20 but production is on v0.16 so this isn't working on production

**Comment by dakshkhetan** [comment]
I think production has v0.15.x
