### ISSUE TITLE
Read.md need to be edited

### ISSUE THREAD

**Issue by rakshitgarg99** [coding-blocks/ide#351]
1. Language supported and Theme numbers are wrong.
![Screenshot (84)](https://user-images.githubusercontent.com/37021771/82457032-94e3fb00-9ad2-11ea-988d-85e4d7743deb.png)
![Screenshot (85)](https://user-images.githubusercontent.com/37021771/82457035-96152800-9ad2-11ea-86f4-063fe1c10af9.png)
![Screenshot (86)](https://user-images.githubusercontent.com/37021771/82457041-97465500-9ad2-11ea-8819-7b29d76657cb.png)

2. There is no Full-screen mode available in IDE

**Comment by mnb27** [comment]
@rakshitgarg99 Editor can go fullscreen mode. (press fn + F11)

**Comment by girishgargcool** [comment]
Is this issue still open?

**Comment by Sujal123456** [comment]
Is this issue still open?
