### ISSUE TITLE
No option to close settings  

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/ide#355]
Once opened settings cannot be closed unless we go to VIEW and click SETTINGS again. We can add a close button for this (right to Reset Defaults).
![Screenshot from 2020-05-21 01-29-23](https://user-images.githubusercontent.com/52792904/82491870-e6a47980-9b02-11ea-9e25-fabd3c1233ab.png)

**Comment by hereisnaman** [comment]
Settings are being moved to a modal https://github.com/coding-blocks/ide/issues/323#issuecomment-631672015
