### ISSUE TITLE
Dropdown gets hidden behind the In/Out Box

### ISSUE THREAD

**Issue by gurrrung** [coding-blocks/ide#357]
![Screenshot from 2020-05-21 08-33-52](https://user-images.githubusercontent.com/30543444/82518846-e1b0eb80-9b3d-11ea-9f77-5e53a517b172.png)

**Comment by hereisnaman** [comment]
mention the resolution.

**Comment by gurrrung** [comment]
I just pulled the box up until it overlaps with dropdown.

**Comment by hereisnaman** [comment]
trying hard to find bugs haan.

**Comment by gurrrung** [comment]
Yeah, it was difficult to find than to solve.
