### ISSUE TITLE
Error after npm run dev

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/ide#365]
After running npm install successfully when we run `npm run dev` it gives an error:

"Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'"

I am working  on this.

**Comment by samagragupta** [comment]
@abhishek97 Please assign bounty to this.

**Comment by ankiiitraj** [comment]
This is explained here https://github.com/microsoft/monaco-editor-webpack-plugin/issues/92

**Comment by samagragupta** [comment]
@ankiiitraj After that we get another error.

**Comment by ankiiitraj** [comment]
Ok, What I did was install v0.19.0 and there were no error.

**Comment by samagragupta** [comment]
@ankiiitraj This is why I created this issue.

**Comment by samagragupta** [comment]
@hereisnaman Could you please assign bounty to this.
