### ISSUE TITLE
Hide Setting Bar On Clicking Inside IDE

### ISSUE THREAD

**Issue by sutharp777** [coding-blocks/ide#383]
#### Description of  Bug :bug:
 the setting bar should hide after done it's job.

**To Reproduce**
1. Go to view ->setting 
2. After changing settings click on view or anywhere other than view->settings it will not disappear.

**Expected behavior**
   1. It should disappear when we click on  **on anywhere inside ide or on view option** 
        instead of **view -> settings**.
   2. **it makes sense that there is no need of setting bar, hide it.**

**screenshot**
- <img src = "https://i.ibb.co/s1F15CM/ideimg.gif" title = "image is large it might take a while" height="220">

**Would you like to work on the issue?**
- [x] Yes

**Comment by hereisnaman** [comment]
The migration of settings bar to a modal is in progress
