### ISSUE TITLE
Feature Request : Ruler in IDE

### ISSUE THREAD

**Issue by sutharp777** [coding-blocks/ide#390]
# Feature: Ruler
  - Thin **Vertical Line**, that helps in organize our code.
  - Dropdown menu **'Ruler'** in **View** that has several units.
    * ![](https://i.ibb.co/M64z2Sh/likethis.png)
    * **None** for no line. 
    * where units are distance from left.
  ##### this screenshot from sublime text.

![](https://i.ibb.co/XXxjFRp/sublime.png)

**Comment by sutharp777** [comment]
@hereisnaman bhaiya, please review this issue.

**Comment by hereisnaman** [comment]
I don't think if we need it.
