### ISSUE TITLE
Run button should disable for CSV.

### ISSUE THREAD

**Issue by sutharp777** [coding-blocks/ide#404]
## Run button should not run if selected language is CSV.
 - it doesn't make any sense to run a CVS file.
<img src="https://i.ibb.co/XXY8Vhn/csv-run.gif" height=300>

**Comment by sutharp777** [comment]
# #404
@hereisnaman  bhaiya review this issue.

**Comment by abhishek97** [comment]
Run type: CSV is used internally at Coding Blocks. Maybe we can hide it for public frontend.
