### ISSUE TITLE
[bug] [css] the footer is not full width

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/ide#42]
as seen on a full hd monitor, full width window. 

<img width="1439" alt="screen shot 2017-05-27 at 1 27 16 am" src="https://cloud.githubusercontent.com/assets/1327050/26510604/b7f9bcb8-427b-11e7-9472-537492ed5468.png">

**Comment by sirjan13** [comment]
@championswimmer  Fixed : Please Review #44

**Comment by hereisnaman** [comment]
@championswimmer those bugs occurred during merge conflict and have already been resolved: https://github.com/coding-blocks/ide/pull/41
