### ISSUE TITLE
[bug] [css] [alignment] left side of boxes for editor, and input box not aligned 

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/ide#43]
<img width="477" alt="screen shot 2017-05-27 at 1 28 56 am" src="https://cloud.githubusercontent.com/assets/1327050/26510656/f0d34a68-427b-11e7-9b12-ace2749bc407.png">

**Comment by niketmishra** [comment]
Done.

**Comment by hereisnaman** [comment]
@championswimmer those bugs occurred during merge conflict and have already been resolved under the PR: https://github.com/coding-blocks/ide/pull/41 yesterday only. Please merge this one.

**Comment by hereisnaman** [comment]
@championswimmer PR has been merged. This is resolved.
