### ISSUE TITLE
make the custom input toggle-able

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/ide#50]
do not show custom input box by default
add a button "custom input" on the editor,
when we click that, only then make the custom input box visible.

**Comment by hereisnaman** [comment]
@championswimmer done: https://github.com/coding-blocks/ide/pull/52

**Comment by abhishek97** [comment]
@astu9880  @hereisnaman 
Neither #51 nor #52 fixes this. Please take care of the case where if we write something in custom input and then toggle it off. The program should run as if there was not input provided. Currently none of the pull request fixes this.

**Comment by hereisnaman** [comment]
@abhishek97 @championswimmer I resolved that now by setting input box html to null

**Comment by abhishek97** [comment]
@hereisnaman  Where? , i don't see any changes in you PR.

**Comment by astu9880** [comment]
@abhishek97  Thank you! Made changes. also i think that the input provided shouldn't completely vanish when input box is toggled off so i saved it in local storage.
In case user doesn't mean to turn custom input off and hit it by chance, data shouldn't be lost

**Comment by Vatsalgarg1617** [comment]
@championswimmer  I resolved the custom input toggle problem. Please merge: #52

**Comment by astu9880** [comment]
@championswimmer Sir please review #51 xD I need to push more commits for this repository but am allowed only one fork!

**Comment by abhishek97** [comment]
@astu9880 please use different branch in that case. you can read about branches here :
 https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

You are not bind to one thing at a time. While this pr is waiting for approval. Fork another branch from `https://github.com/coding-blocks master` and commit to that branch. Keep the contributions coming . 😸
