### ISSUE TITLE
IDE should have more height, more separation from Footer.

### ISSUE THREAD

**Issue by prateek27** [coding-blocks/ide#56]
When the page open only IDE should take maximum height. Footer shouldn't be visible, unless page is scrolled down.

![ide_issue](https://cloud.githubusercontent.com/assets/5269147/26527709/6b2f75de-43b7-11e7-9f1e-1d8fcbe6b251.png)

**Comment by realslimshanky** [comment]
Hi, I've fixed this issue please review the code.
You can test my PR by visiting https://realslimshanky.github.io/ide/

**Comment by hereisnaman** [comment]
@prateek27 already fixed https://github.com/coding-blocks/ide/pull/54
 with editor width to height ratio 16:9.

**Comment by realslimshanky** [comment]
@hereisnaman but navbar needed to be moved out of screen explicitly as @prateek27 said.

**Comment by hereisnaman** [comment]
@realslimshanky footer should be moved not navbar and that I have already done, check my PR: https://github.com/coding-blocks/ide/pull/54 , it have the screen shots. I have used 7% and 9% top and bottom margins. 

If you just set the height to lets say 600px then it the footer will again start appearing if the screen height is much height. Dynamically setting up height according to width is I guess better. :)

**Comment by realslimshanky** [comment]
@hereisnaman looks nice. sorry for the confusion I've fixed my comment.

**Comment by hereisnaman** [comment]
@realslimshanky No its okay. Always nice to get suggestions. Thanks :)

**Comment by realslimshanky** [comment]
Anytime :)

**Comment by omerjerk** [comment]
@prateek27 Please close this if the issue has been resolved.
