### ISSUE TITLE
language button should have a dropdown 

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/ide#59]
for good UX : user should get a hint that language can be dropped down and changed.

**Comment by abhishek97** [comment]
#60  Adds a caret after language as a visual clue for dropdown.

![screen shot 2017-05-28 at 7 11 35 pm](https://cloud.githubusercontent.com/assets/8109774/26529210/8ae23c50-43d9-11e7-88fa-2b1e5c358164.png)

**Comment by hereisnaman** [comment]
@championswimmer already done sir: https://github.com/coding-blocks/ide/pull/58

Also @abhishek97 has not added caret when the language button html is updated when file is uploaded. I have included it at both places. Please merge : https://github.com/coding-blocks/ide/pull/58

**Comment by abhishek97** [comment]
@hereisnaman  There is a caret also when a file is uploaded. Please read the code first.

**Comment by hereisnaman** [comment]
@abhishek97 okay sorry, removing my comment. Well Done. :)

**Comment by abhishek97** [comment]
@championswimmer  #61  doesn't take care of care when a file is uploaded. Then the caret is removed.
