### ISSUE TITLE
save the state on user's localStorage

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/ide#65]
- [ ] save code 
-  [ ] save the language option
 - [ ] save the custom input if any
 - [ ] use a onchange debounce on the editor. save every 30 sec. (like composing mail on Gmail)

**Comment by championswimmer** [comment]
Bounty = 300

**Comment by hereisnaman** [comment]
@championswimmer code and language already getting saved using save button. I did in PR: https://github.com/coding-blocks/ide/pull/26 (already merged). Theme and other sittings also getting saved in the PR:  https://github.com/coding-blocks/ide/pull/63 (not merged). working on to integrate input and save every 30 sec in the same PR.

**Comment by hereisnaman** [comment]
@championswimmer changes pushed to PR: https://github.com/coding-blocks/ide/pull/63

Already the code and language is getting saved as done by me in PR: https://github.com/coding-blocks/ide/pull/26

In PR: https://github.com/coding-blocks/ide/pull/63 code and all other data, including Theme, Fonts, Font Size, input, file name and much more automatically gets saved after every 30 seconds.

**Comment by hereisnaman** [comment]
@championswimmer @prateek27 please also add addition bounty to https://github.com/coding-blocks/ide/pull/63 as including many more features.

**Comment by hereisnaman** [comment]
@championswimmer @prateek27 thanks for merging my previous PR. In the new PR: https://github.com/coding-blocks/ide/pull/67 I have made some updates. 

Currently the code gets automatically saved every 30 seconds. But in the new PR I have made the provisions to make it only save when changes are there. 

I have made few Fixes too and added fadeIn and fadeOut text below the editor for autosave.

Please give it a look :).

**Comment by hereisnaman** [comment]
@championswimmer The other PR is also merged. Now to code gets saves ever 30 sec, only if changes are there.
