### ISSUE TITLE
Support for uploading a file from client system

### ISSUE THREAD

**Issue by Akshay-parashar** [coding-blocks/ide#8]
A user should be able to upload the code he wrote from whatever IDE or texteditor he is using or is comfortable with.

**Comment by sohini-roy** [comment]
Can I work on this issue :)

**Comment by omerjerk** [comment]
Hi @sohini-roy,

You can definitely work on this issue. One other person has already submitted a partial pull request for this. The bounty, however, will be given to one person only.

- Umair

**Comment by Akshay-parashar** [comment]
Added Support for file upload #19

**Comment by Akshay-parashar** [comment]
Added Support for file upload #19
