### ISSUE TITLE
[bug] Ace editor supports only mono-space fonts

### ISSUE THREAD

**Issue by astu9880** [coding-blocks/ide#82]
Ace editor supports only monospace fonts. Having lucida console introduces bug like below (Cursor and text mis-alignment) It would be better to not use non-monospace font
![bug](https://user-images.githubusercontent.com/18186457/27119677-63da2c6c-50fe-11e7-8511-25b46d824f04.png)

**Comment by hereisnaman** [comment]
resolved: https://github.com/coding-blocks/ide/pull/83
