### ISSUE TITLE
in full screen layout, also allow showing output in bottom

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/ide#90]
the output box should be toggle-able. so it is visible only if required.

**Comment by hereisnaman** [comment]
@championswimmer should provide button for toggle or just automatically display it after run? and hide it with clear all.

**Comment by sohini-roy** [comment]
#92 
@championswimmer please have a look and review

**Comment by championswimmer** [comment]
@hereisnaman can you work on this  too ?

**Comment by hereisnaman** [comment]
@championswimmer sure, working on first implementing full screen then adding some features to it.
